[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ytmusicfs"
version = "0.1.0"
description = "YouTube Music FUSE filesystem"
readme = "README.md"
authors = [{ name = "astrovm", email = "ytmusicfs@4st.li" }]
license = { text = "MIT" }
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: End Users/Desktop",
  "Topic :: Multimedia :: Sound/Audio",
  "Topic :: System :: Filesystems",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Operating System :: POSIX :: Linux",
]
keywords = ["youtube", "music", "filesystem", "fuse", "streaming"]
dependencies = [
  "fusepy>=3.0.1",
  "ytmusicapi>=1.10.2",
  "requests>=2.31.0",
  "google-auth>=2.22.0",
  "google-auth-oauthlib>=1.0.0",
  "yt-dlp>=2024.2.28",
  "packaging>=23.0",
]
requires-python = ">=3.7"

[project.optional-dependencies]
dev = [
  "pytest>=7.0.0",
  "pytest-cov>=4.0.0",
  "black>=23.0.0",
  "isort>=5.12.0",
  "flake8>=6.0.0",
  "mypy>=1.0.0",
]

[project.urls]
"Homepage" = "https://github.com/astrovm/ytmusicfs"
"Bug Tracker" = "https://github.com/astrovm/ytmusicfs/issues"
"Source" = "https://github.com/astrovm/ytmusicfs"

[project.scripts]
ytmusicfs = "ytmusicfs.cli:main"
ytmusicfs-oauth = "ytmusicfs.utils.oauth_setup:main"

[tool.setuptools]
packages = ["ytmusicfs", "ytmusicfs.utils"]

[tool.black]
line-length = 88
target-version = ["py37", "py38", "py39", "py310", "py311"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
